# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a65fe2d1b39ed14f03b794adac3378ebc3d229e11260289a1610175f347c9c319e6c3a2dc8d7a8cc34038154ed1d560713277ca8c8d60c6c79dd9a7b0fcf6f92

test:
  secret_key_base: 3bd55b01e1deb1a3c69ff2e00ec5b6f3421422b8729ecb50cfc5fb6b970d62dfa71b5e5fae1955f8b926e0679583868f29dcb2b127c84a24ddc98b722be7c0e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
